name: deploy-gcs-test
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1

      - name: Install npm desp
        run: npm i

      - name: Build
        run: npm run build:dev

      - id: upload-files
        uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
        with:
          path: /dist/
          destination: steel-test